Feat/core lib
atomicagro/core pull request #1
Opened 2023-11-10 14:44 UTC by josetorquatoseedz

# Title
Core library creation.

## 🚀 Motivation
Centralizing services in an application means grouping common or logical functionalities in a single location, reducing code duplication, simplifying maintenance, ensuring consistency and promoting reusability.

## 🛠 Proposed Solution
The proposed solution involves the implementation of a library (lib) that centralizes essential services in our application. This library initially offers two main functionalities: searching for CEP by coordinates and obtaining the IBGE code by CEP. It can be expanded and added more features as we need.

## 📝 Additional Information

## 📋 Checklist:

- [x] My code follows the established project standards 🌟
- [x] I did a thorough self-review of my code 🧐
- [x] I added tests to ensure the effectiveness of my fix or the functionality of my feature ✅
- [x] Both new and existing unit tests pass locally with my changes ✔️

2023-11-13 15:07 UTC, ivanguimam commented
Cara cria esses dois arquivos no projeto:

.vscode/extensions.json
```json
{
  "recommendations": ["dbaeumer.vscode-eslint", "esbenp.prettier-vscode"]
}
```

.vscode/settings.json
```json
{
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.organizeImports": true
  },
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.tabSize": 2,
  "files.exclude": {
    "**/__snapshots__": true,
    "**/.DS_Store": true
  },
  "typescript.tsdk": "node_modules/typescript/lib",
  "[jsonc]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "[json]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "typescript.preferences.importModuleSpecifier": "non-relative",
  "typescript.preferences.quoteStyle": "single"
}
```

2023-11-13 18:16 UTC, ivanguimam requested changes

2023-11-13 18:16 UTC, ivanguimam commented on .vscode/launch.json
> +      "type": "node",
Essa config de E2E não é necessária

2023-11-13 18:16 UTC, ivanguimam commented on package.json
> +    "axios-mock-adapter": "^1.22.0",
Instalar versão fixa

2023-11-13 18:16 UTC, ivanguimam commented on package.json
> +    "jest": "^29.7.0",
Instalar versão fixa

2023-11-13 18:16 UTC, ivanguimam commented on package.json
> +    "ts-node": "^10.0.0",
Instalar versão fixa

2023-11-13 18:16 UTC, ivanguimam commented on package.json
> +    "tsc-alias": "^1.8.8",
Instalar versão fixa

2023-11-13 18:16 UTC, ivanguimam commented on package.json
> +    "dotenv": "^16.3.1",
Instalar versão fixa

2023-11-13 18:16 UTC, ivanguimam commented on package.json
> +    "inversify": "^6.0.2",
Instalar versão fixa

2023-11-13 18:16 UTC, ivanguimam commented on package.json
> +    "reflect-metadata": "^0.1.13"
Instalar versão fixa

2023-11-13 18:16 UTC, ivanguimam commented on src/api/GoogleMaps/index.ts
> +    this.url = 'https://maps.googleapis.com/maps/api/geocode/json';
Pq dessa url aqui e não na função `findZipCodeByCoordinates`. Você pode configurar um baseUrl no axios.create `https://maps.googleapis.com/maps/api` e o restante na função `findZipCodeByCoordinates`. Mas não tem muito pq dessa url na classe

2023-11-13 18:16 UTC, ivanguimam commented on src/api/GoogleMaps/tests/findZipCodeByCoordinates.spec.ts
> +    const coordinates = { lat: '123', long: '456' };
Usar a tipagem

2023-11-13 18:16 UTC, ivanguimam commented on src/api/Postmon/interfaces/infoCity.ts
> +export interface InfoCity {
CityInfo

2023-11-13 18:16 UTC, ivanguimam commented on src/api/Postmon/tests/findIbgeCodeByZipCode.spec.ts
> +    mockAxios.onGet(`/cep/${zipCode}`).reply(200, expectedData);
HttpStatusCode.ok

2023-11-13 18:16 UTC, ivanguimam commented on src/api/Postmon/tests/findIbgeCodeByZipCode.spec.ts
> +    mockAxios.onGet(`/cep/${zipCode}`).reply(404, error);
HttpStatusCode.BadRequest

2023-11-13 18:16 UTC, ivanguimam commented on src/api/Postmon/tests/findIbgeCodeByZipCode.spec.ts
> +      expect((e as RequestError).status).toBe(404);
HttpStatusCode.BadRequest

2023-11-13 18:16 UTC, ivanguimam commented on src/api/inverse.ts
Cara eu chamaria esse arquivo de `ioc.ts` (Inverse of Control), ou pensar em um nome melhor, mas só `inverse.ts` ficou ruim

2023-11-13 18:16 UTC, ivanguimam commented on src/api/inverse.ts
> +import { TYPES } from '@configs/types';
Eu criaria um arquivo Types dentro de api com todos os Types para da parte de api, e ai nesse geral do config eu importaria o types de api e edicionaria ele em um types geral (pode me chamar, sei que ficou confuso)

2023-11-13 18:16 UTC, ivanguimam commented on src/api/inverse.ts
> +export function configureApi(container: Container) {
Pode chamar essa função somente de `configure` mesmo ou `setup`, pra manter um padrão de nomenclatura de todas as funções que fazem esse setup do ioc

2023-11-13 18:16 UTC, ivanguimam commented on src/configs/inverse.ts
> +export function configureContainer() {
Pode chamar essa função somente de `configure` mesmo ou `setup`, pra manter um padrão de nomenclatura de todas as funções que fazem esse setup do ioc

2023-11-13 18:16 UTC, ivanguimam commented on src/api/GoogleMaps/index.ts
> +      key: token,
O que é esse token mesmo? Pq ele recebe isso e não ta como uma conf defualt do axios ou em uma .env?

2023-11-13 18:16 UTC, ivanguimam commented on src/services/CityService/index.ts
> +    return await this.googleMapsApi.findZipCodeByCoordinates(coordinates, token);
Esse return `await` é desnecessário

2023-11-13 18:16 UTC, ivanguimam commented on src/services/CityService/index.ts
> +    return await this.postmonApi.findIbgeCodeByZipCode(zipCode);
Esse return `await` é desnecessário

2023-11-13 18:16 UTC, ivanguimam commented on src/services/CityService/tests/getIbgeCodeByZipCode.spec.ts
> +  it('should return ibgeCode', async () => {
Me chamar pois é mais fácil de explicar
```ts
  beforeEach(() => container.snapshot())

  afterEach(() => container.restore())
```

2023-11-13 18:16 UTC, ivanguimam commented on src/services/CityService/tests/getIbgeCodeByZipCode.spec.ts
> +      expect(e).toBeInstanceOf(RequestError);
Uai, não era pra lançår um `IbgeCodeNotFoundError`?

2023-11-13 18:16 UTC, ivanguimam commented on src/services/CityService/tests/getZipCodeByCoordinates.spec.ts
> +    const spy = jest.fn().mockRejectedValue(new RequestError({ data: 'Invalid token', status: 401 }));
HttpStatusCode.Unalthorized

2023-11-13 18:16 UTC, ivanguimam commented on src/services/CityService/tests/getZipCodeByCoordinates.spec.ts
> +      expect((e as RequestError).status).toStrictEqual(401);
HttpStatusCode.Unalthorized

2023-11-14 13:04 UTC, josetorquatoseedz commented on src/api/Postmon/tests/findIbgeCodeByZipCode.spec.ts
> +    mockAxios.onGet(`/cep/${zipCode}`).reply(404, error);
HttpStatusCode.NotFound

2023-11-20 17:54 UTC, ivanguimam requested changes

2023-11-20 17:54 UTC, ivanguimam commented on src/api/GoogleMaps/index.ts
> +  url: string;
Pra que esse `url` aqui?

2023-11-20 17:54 UTC, ivanguimam commented on src/services/CityService/tests/getIbgeCodeByZipCode.spec.ts
> +    container
```ts
it('should return ibgeCode', async () => {
  const ibgeCode = '4304606';
  const zipCode = '92440-540';

  const googleMapsApi = new GoogleMapsApi();
  const postmon = new Postmon();
  const spy = jest.spyOn(postmon, 'findIbgeCodeByZipCode').mockResolvedValue({ ibgeCode });

  container.bind<GoogleMaps>(TYPES.googleMaps).toConstantValue(googleMapsApi);
  container.bind<Postmon>(TYPES.postmon).toConstantValue(postmon);

  const cityService = container.get(TYPES.CityService);

  const result = await cityService.getIbgeCodeByZipCode(zipCode);

  expect(result).toMatchObject({ ibgeCode });
  expect(spy).toHaveBeenCalledWith(zipCode);
});
```

2023-11-20 19:45 UTC, ivanguimam approved these changes

2023-11-20 19:45 UTC, merged